//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34209
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeaRoom.ProductServices {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="T_Products", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class T_Products : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ProductIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductNameField;
        
        private System.Nullable<int> IsInventoryField;
        
        private System.Nullable<int> InventoryIDField;
        
        private System.Nullable<int> LostInventoryField;
        
        private System.Nullable<decimal> MemberPriceField;
        
        private System.Nullable<decimal> PriceField;
        
        private System.Nullable<int> ProductSourceField;
        
        private System.Nullable<int> ProductTypeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductTypeNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ProductID {
            get {
                return this.ProductIDField;
            }
            set {
                if ((this.ProductIDField.Equals(value) != true)) {
                    this.ProductIDField = value;
                    this.RaisePropertyChanged("ProductID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ProductName {
            get {
                return this.ProductNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductNameField, value) != true)) {
                    this.ProductNameField = value;
                    this.RaisePropertyChanged("ProductName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.Nullable<int> IsInventory {
            get {
                return this.IsInventoryField;
            }
            set {
                if ((this.IsInventoryField.Equals(value) != true)) {
                    this.IsInventoryField = value;
                    this.RaisePropertyChanged("IsInventory");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.Nullable<int> InventoryID {
            get {
                return this.InventoryIDField;
            }
            set {
                if ((this.InventoryIDField.Equals(value) != true)) {
                    this.InventoryIDField = value;
                    this.RaisePropertyChanged("InventoryID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.Nullable<int> LostInventory {
            get {
                return this.LostInventoryField;
            }
            set {
                if ((this.LostInventoryField.Equals(value) != true)) {
                    this.LostInventoryField = value;
                    this.RaisePropertyChanged("LostInventory");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.Nullable<decimal> MemberPrice {
            get {
                return this.MemberPriceField;
            }
            set {
                if ((this.MemberPriceField.Equals(value) != true)) {
                    this.MemberPriceField = value;
                    this.RaisePropertyChanged("MemberPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.Nullable<decimal> Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.Nullable<int> ProductSource {
            get {
                return this.ProductSourceField;
            }
            set {
                if ((this.ProductSourceField.Equals(value) != true)) {
                    this.ProductSourceField = value;
                    this.RaisePropertyChanged("ProductSource");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public System.Nullable<int> ProductTypeID {
            get {
                return this.ProductTypeIDField;
            }
            set {
                if ((this.ProductTypeIDField.Equals(value) != true)) {
                    this.ProductTypeIDField = value;
                    this.RaisePropertyChanged("ProductTypeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string ProductTypeName {
            get {
                return this.ProductTypeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductTypeNameField, value) != true)) {
                    this.ProductTypeNameField = value;
                    this.RaisePropertyChanged("ProductTypeName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProductServices.ProdctServicesSoap")]
    public interface ProdctServicesSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 GetProductListResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetProductList", ReplyAction="*")]
        TeaRoom.ProductServices.GetProductListResponse GetProductList(TeaRoom.ProductServices.GetProductListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/GetProductList", ReplyAction="*")]
        System.IAsyncResult BeginGetProductList(TeaRoom.ProductServices.GetProductListRequest request, System.AsyncCallback callback, object asyncState);
        
        TeaRoom.ProductServices.GetProductListResponse EndGetProductList(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProductListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProductList", Namespace="http://tempuri.org/", Order=0)]
        public TeaRoom.ProductServices.GetProductListRequestBody Body;
        
        public GetProductListRequest() {
        }
        
        public GetProductListRequest(TeaRoom.ProductServices.GetProductListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetProductListRequestBody {
        
        public GetProductListRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProductListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProductListResponse", Namespace="http://tempuri.org/", Order=0)]
        public TeaRoom.ProductServices.GetProductListResponseBody Body;
        
        public GetProductListResponse() {
        }
        
        public GetProductListResponse(TeaRoom.ProductServices.GetProductListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetProductListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TeaRoom.ProductServices.T_Products[] GetProductListResult;
        
        public GetProductListResponseBody() {
        }
        
        public GetProductListResponseBody(TeaRoom.ProductServices.T_Products[] GetProductListResult) {
            this.GetProductListResult = GetProductListResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ProdctServicesSoapChannel : TeaRoom.ProductServices.ProdctServicesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetProductListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetProductListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public TeaRoom.ProductServices.T_Products[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((TeaRoom.ProductServices.T_Products[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProdctServicesSoapClient : System.ServiceModel.ClientBase<TeaRoom.ProductServices.ProdctServicesSoap>, TeaRoom.ProductServices.ProdctServicesSoap {
        
        private BeginOperationDelegate onBeginGetProductListDelegate;
        
        private EndOperationDelegate onEndGetProductListDelegate;
        
        private System.Threading.SendOrPostCallback onGetProductListCompletedDelegate;
        
        public ProdctServicesSoapClient() {
        }
        
        public ProdctServicesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProdctServicesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProdctServicesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProdctServicesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<GetProductListCompletedEventArgs> GetProductListCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TeaRoom.ProductServices.GetProductListResponse TeaRoom.ProductServices.ProdctServicesSoap.GetProductList(TeaRoom.ProductServices.GetProductListRequest request) {
            return base.Channel.GetProductList(request);
        }
        
        public TeaRoom.ProductServices.T_Products[] GetProductList() {
            TeaRoom.ProductServices.GetProductListRequest inValue = new TeaRoom.ProductServices.GetProductListRequest();
            inValue.Body = new TeaRoom.ProductServices.GetProductListRequestBody();
            TeaRoom.ProductServices.GetProductListResponse retVal = ((TeaRoom.ProductServices.ProdctServicesSoap)(this)).GetProductList(inValue);
            return retVal.Body.GetProductListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult TeaRoom.ProductServices.ProdctServicesSoap.BeginGetProductList(TeaRoom.ProductServices.GetProductListRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetProductList(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetProductList(System.AsyncCallback callback, object asyncState) {
            TeaRoom.ProductServices.GetProductListRequest inValue = new TeaRoom.ProductServices.GetProductListRequest();
            inValue.Body = new TeaRoom.ProductServices.GetProductListRequestBody();
            return ((TeaRoom.ProductServices.ProdctServicesSoap)(this)).BeginGetProductList(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TeaRoom.ProductServices.GetProductListResponse TeaRoom.ProductServices.ProdctServicesSoap.EndGetProductList(System.IAsyncResult result) {
            return base.Channel.EndGetProductList(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public TeaRoom.ProductServices.T_Products[] EndGetProductList(System.IAsyncResult result) {
            TeaRoom.ProductServices.GetProductListResponse retVal = ((TeaRoom.ProductServices.ProdctServicesSoap)(this)).EndGetProductList(result);
            return retVal.Body.GetProductListResult;
        }
        
        private System.IAsyncResult OnBeginGetProductList(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginGetProductList(callback, asyncState);
        }
        
        private object[] OnEndGetProductList(System.IAsyncResult result) {
            TeaRoom.ProductServices.T_Products[] retVal = this.EndGetProductList(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetProductListCompleted(object state) {
            if ((this.GetProductListCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetProductListCompleted(this, new GetProductListCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetProductListAsync() {
            this.GetProductListAsync(null);
        }
        
        public void GetProductListAsync(object userState) {
            if ((this.onBeginGetProductListDelegate == null)) {
                this.onBeginGetProductListDelegate = new BeginOperationDelegate(this.OnBeginGetProductList);
            }
            if ((this.onEndGetProductListDelegate == null)) {
                this.onEndGetProductListDelegate = new EndOperationDelegate(this.OnEndGetProductList);
            }
            if ((this.onGetProductListCompletedDelegate == null)) {
                this.onGetProductListCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetProductListCompleted);
            }
            base.InvokeAsync(this.onBeginGetProductListDelegate, null, this.onEndGetProductListDelegate, this.onGetProductListCompletedDelegate, userState);
        }
    }
}
