//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34209
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeaRoom.OperatServices {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="T_Operat_User", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class T_Operat_User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        private int OperatIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PassWordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OperatNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelField;
        
        private System.Nullable<int> ActiveField;
        
        private System.Nullable<int> OperatGroupField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GroupNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int OperatID {
            get {
                return this.OperatIDField;
            }
            set {
                if ((this.OperatIDField.Equals(value) != true)) {
                    this.OperatIDField = value;
                    this.RaisePropertyChanged("OperatID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string PassWord {
            get {
                return this.PassWordField;
            }
            set {
                if ((object.ReferenceEquals(this.PassWordField, value) != true)) {
                    this.PassWordField = value;
                    this.RaisePropertyChanged("PassWord");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string OperatName {
            get {
                return this.OperatNameField;
            }
            set {
                if ((object.ReferenceEquals(this.OperatNameField, value) != true)) {
                    this.OperatNameField = value;
                    this.RaisePropertyChanged("OperatName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Tel {
            get {
                return this.TelField;
            }
            set {
                if ((object.ReferenceEquals(this.TelField, value) != true)) {
                    this.TelField = value;
                    this.RaisePropertyChanged("Tel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.Nullable<int> Active {
            get {
                return this.ActiveField;
            }
            set {
                if ((this.ActiveField.Equals(value) != true)) {
                    this.ActiveField = value;
                    this.RaisePropertyChanged("Active");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.Nullable<int> OperatGroup {
            get {
                return this.OperatGroupField;
            }
            set {
                if ((this.OperatGroupField.Equals(value) != true)) {
                    this.OperatGroupField = value;
                    this.RaisePropertyChanged("OperatGroup");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string GroupName {
            get {
                return this.GroupNameField;
            }
            set {
                if ((object.ReferenceEquals(this.GroupNameField, value) != true)) {
                    this.GroupNameField = value;
                    this.RaisePropertyChanged("GroupName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OperatServices.OperatServicesSoap")]
    public interface OperatServicesSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 strUserName 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UserLogin", ReplyAction="*")]
        TeaRoom.OperatServices.UserLoginResponse UserLogin(TeaRoom.OperatServices.UserLoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/UserLogin", ReplyAction="*")]
        System.IAsyncResult BeginUserLogin(TeaRoom.OperatServices.UserLoginRequest request, System.AsyncCallback callback, object asyncState);
        
        TeaRoom.OperatServices.UserLoginResponse EndUserLogin(System.IAsyncResult result);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 GetOperatListResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOperatList", ReplyAction="*")]
        TeaRoom.OperatServices.GetOperatListResponse GetOperatList(TeaRoom.OperatServices.GetOperatListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/GetOperatList", ReplyAction="*")]
        System.IAsyncResult BeginGetOperatList(TeaRoom.OperatServices.GetOperatListRequest request, System.AsyncCallback callback, object asyncState);
        
        TeaRoom.OperatServices.GetOperatListResponse EndGetOperatList(System.IAsyncResult result);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 Password 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveOrUpdateOperat", ReplyAction="*")]
        TeaRoom.OperatServices.SaveOrUpdateOperatResponse SaveOrUpdateOperat(TeaRoom.OperatServices.SaveOrUpdateOperatRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/SaveOrUpdateOperat", ReplyAction="*")]
        System.IAsyncResult BeginSaveOrUpdateOperat(TeaRoom.OperatServices.SaveOrUpdateOperatRequest request, System.AsyncCallback callback, object asyncState);
        
        TeaRoom.OperatServices.SaveOrUpdateOperatResponse EndSaveOrUpdateOperat(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UserLoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UserLogin", Namespace="http://tempuri.org/", Order=0)]
        public TeaRoom.OperatServices.UserLoginRequestBody Body;
        
        public UserLoginRequest() {
        }
        
        public UserLoginRequest(TeaRoom.OperatServices.UserLoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UserLoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strUserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string strPassword;
        
        public UserLoginRequestBody() {
        }
        
        public UserLoginRequestBody(string strUserName, string strPassword) {
            this.strUserName = strUserName;
            this.strPassword = strPassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UserLoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UserLoginResponse", Namespace="http://tempuri.org/", Order=0)]
        public TeaRoom.OperatServices.UserLoginResponseBody Body;
        
        public UserLoginResponse() {
        }
        
        public UserLoginResponse(TeaRoom.OperatServices.UserLoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UserLoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TeaRoom.OperatServices.T_Operat_User UserLoginResult;
        
        public UserLoginResponseBody() {
        }
        
        public UserLoginResponseBody(TeaRoom.OperatServices.T_Operat_User UserLoginResult) {
            this.UserLoginResult = UserLoginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOperatListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetOperatList", Namespace="http://tempuri.org/", Order=0)]
        public TeaRoom.OperatServices.GetOperatListRequestBody Body;
        
        public GetOperatListRequest() {
        }
        
        public GetOperatListRequest(TeaRoom.OperatServices.GetOperatListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetOperatListRequestBody {
        
        public GetOperatListRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOperatListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetOperatListResponse", Namespace="http://tempuri.org/", Order=0)]
        public TeaRoom.OperatServices.GetOperatListResponseBody Body;
        
        public GetOperatListResponse() {
        }
        
        public GetOperatListResponse(TeaRoom.OperatServices.GetOperatListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetOperatListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TeaRoom.OperatServices.T_Operat_User[] GetOperatListResult;
        
        public GetOperatListResponseBody() {
        }
        
        public GetOperatListResponseBody(TeaRoom.OperatServices.T_Operat_User[] GetOperatListResult) {
            this.GetOperatListResult = GetOperatListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveOrUpdateOperatRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveOrUpdateOperat", Namespace="http://tempuri.org/", Order=0)]
        public TeaRoom.OperatServices.SaveOrUpdateOperatRequestBody Body;
        
        public SaveOrUpdateOperatRequest() {
        }
        
        public SaveOrUpdateOperatRequest(TeaRoom.OperatServices.SaveOrUpdateOperatRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaveOrUpdateOperatRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string UserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string OperatName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Tel;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Active;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string OperatGroup;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string OperatID;
        
        public SaveOrUpdateOperatRequestBody() {
        }
        
        public SaveOrUpdateOperatRequestBody(string Password, string UserName, string OperatName, string Tel, string Active, string OperatGroup, string OperatID) {
            this.Password = Password;
            this.UserName = UserName;
            this.OperatName = OperatName;
            this.Tel = Tel;
            this.Active = Active;
            this.OperatGroup = OperatGroup;
            this.OperatID = OperatID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveOrUpdateOperatResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveOrUpdateOperatResponse", Namespace="http://tempuri.org/", Order=0)]
        public TeaRoom.OperatServices.SaveOrUpdateOperatResponseBody Body;
        
        public SaveOrUpdateOperatResponse() {
        }
        
        public SaveOrUpdateOperatResponse(TeaRoom.OperatServices.SaveOrUpdateOperatResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaveOrUpdateOperatResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int SaveOrUpdateOperatResult;
        
        public SaveOrUpdateOperatResponseBody() {
        }
        
        public SaveOrUpdateOperatResponseBody(int SaveOrUpdateOperatResult) {
            this.SaveOrUpdateOperatResult = SaveOrUpdateOperatResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface OperatServicesSoapChannel : TeaRoom.OperatServices.OperatServicesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserLoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public UserLoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public TeaRoom.OperatServices.T_Operat_User Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((TeaRoom.OperatServices.T_Operat_User)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetOperatListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetOperatListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public TeaRoom.OperatServices.T_Operat_User[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((TeaRoom.OperatServices.T_Operat_User[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SaveOrUpdateOperatCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public SaveOrUpdateOperatCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OperatServicesSoapClient : System.ServiceModel.ClientBase<TeaRoom.OperatServices.OperatServicesSoap>, TeaRoom.OperatServices.OperatServicesSoap {
        
        private BeginOperationDelegate onBeginUserLoginDelegate;
        
        private EndOperationDelegate onEndUserLoginDelegate;
        
        private System.Threading.SendOrPostCallback onUserLoginCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetOperatListDelegate;
        
        private EndOperationDelegate onEndGetOperatListDelegate;
        
        private System.Threading.SendOrPostCallback onGetOperatListCompletedDelegate;
        
        private BeginOperationDelegate onBeginSaveOrUpdateOperatDelegate;
        
        private EndOperationDelegate onEndSaveOrUpdateOperatDelegate;
        
        private System.Threading.SendOrPostCallback onSaveOrUpdateOperatCompletedDelegate;
        
        public OperatServicesSoapClient() {
        }
        
        public OperatServicesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OperatServicesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OperatServicesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OperatServicesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<UserLoginCompletedEventArgs> UserLoginCompleted;
        
        public event System.EventHandler<GetOperatListCompletedEventArgs> GetOperatListCompleted;
        
        public event System.EventHandler<SaveOrUpdateOperatCompletedEventArgs> SaveOrUpdateOperatCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TeaRoom.OperatServices.UserLoginResponse TeaRoom.OperatServices.OperatServicesSoap.UserLogin(TeaRoom.OperatServices.UserLoginRequest request) {
            return base.Channel.UserLogin(request);
        }
        
        public TeaRoom.OperatServices.T_Operat_User UserLogin(string strUserName, string strPassword) {
            TeaRoom.OperatServices.UserLoginRequest inValue = new TeaRoom.OperatServices.UserLoginRequest();
            inValue.Body = new TeaRoom.OperatServices.UserLoginRequestBody();
            inValue.Body.strUserName = strUserName;
            inValue.Body.strPassword = strPassword;
            TeaRoom.OperatServices.UserLoginResponse retVal = ((TeaRoom.OperatServices.OperatServicesSoap)(this)).UserLogin(inValue);
            return retVal.Body.UserLoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult TeaRoom.OperatServices.OperatServicesSoap.BeginUserLogin(TeaRoom.OperatServices.UserLoginRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginUserLogin(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginUserLogin(string strUserName, string strPassword, System.AsyncCallback callback, object asyncState) {
            TeaRoom.OperatServices.UserLoginRequest inValue = new TeaRoom.OperatServices.UserLoginRequest();
            inValue.Body = new TeaRoom.OperatServices.UserLoginRequestBody();
            inValue.Body.strUserName = strUserName;
            inValue.Body.strPassword = strPassword;
            return ((TeaRoom.OperatServices.OperatServicesSoap)(this)).BeginUserLogin(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TeaRoom.OperatServices.UserLoginResponse TeaRoom.OperatServices.OperatServicesSoap.EndUserLogin(System.IAsyncResult result) {
            return base.Channel.EndUserLogin(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public TeaRoom.OperatServices.T_Operat_User EndUserLogin(System.IAsyncResult result) {
            TeaRoom.OperatServices.UserLoginResponse retVal = ((TeaRoom.OperatServices.OperatServicesSoap)(this)).EndUserLogin(result);
            return retVal.Body.UserLoginResult;
        }
        
        private System.IAsyncResult OnBeginUserLogin(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string strUserName = ((string)(inValues[0]));
            string strPassword = ((string)(inValues[1]));
            return this.BeginUserLogin(strUserName, strPassword, callback, asyncState);
        }
        
        private object[] OnEndUserLogin(System.IAsyncResult result) {
            TeaRoom.OperatServices.T_Operat_User retVal = this.EndUserLogin(result);
            return new object[] {
                    retVal};
        }
        
        private void OnUserLoginCompleted(object state) {
            if ((this.UserLoginCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.UserLoginCompleted(this, new UserLoginCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void UserLoginAsync(string strUserName, string strPassword) {
            this.UserLoginAsync(strUserName, strPassword, null);
        }
        
        public void UserLoginAsync(string strUserName, string strPassword, object userState) {
            if ((this.onBeginUserLoginDelegate == null)) {
                this.onBeginUserLoginDelegate = new BeginOperationDelegate(this.OnBeginUserLogin);
            }
            if ((this.onEndUserLoginDelegate == null)) {
                this.onEndUserLoginDelegate = new EndOperationDelegate(this.OnEndUserLogin);
            }
            if ((this.onUserLoginCompletedDelegate == null)) {
                this.onUserLoginCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnUserLoginCompleted);
            }
            base.InvokeAsync(this.onBeginUserLoginDelegate, new object[] {
                        strUserName,
                        strPassword}, this.onEndUserLoginDelegate, this.onUserLoginCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TeaRoom.OperatServices.GetOperatListResponse TeaRoom.OperatServices.OperatServicesSoap.GetOperatList(TeaRoom.OperatServices.GetOperatListRequest request) {
            return base.Channel.GetOperatList(request);
        }
        
        public TeaRoom.OperatServices.T_Operat_User[] GetOperatList() {
            TeaRoom.OperatServices.GetOperatListRequest inValue = new TeaRoom.OperatServices.GetOperatListRequest();
            inValue.Body = new TeaRoom.OperatServices.GetOperatListRequestBody();
            TeaRoom.OperatServices.GetOperatListResponse retVal = ((TeaRoom.OperatServices.OperatServicesSoap)(this)).GetOperatList(inValue);
            return retVal.Body.GetOperatListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult TeaRoom.OperatServices.OperatServicesSoap.BeginGetOperatList(TeaRoom.OperatServices.GetOperatListRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetOperatList(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetOperatList(System.AsyncCallback callback, object asyncState) {
            TeaRoom.OperatServices.GetOperatListRequest inValue = new TeaRoom.OperatServices.GetOperatListRequest();
            inValue.Body = new TeaRoom.OperatServices.GetOperatListRequestBody();
            return ((TeaRoom.OperatServices.OperatServicesSoap)(this)).BeginGetOperatList(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TeaRoom.OperatServices.GetOperatListResponse TeaRoom.OperatServices.OperatServicesSoap.EndGetOperatList(System.IAsyncResult result) {
            return base.Channel.EndGetOperatList(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public TeaRoom.OperatServices.T_Operat_User[] EndGetOperatList(System.IAsyncResult result) {
            TeaRoom.OperatServices.GetOperatListResponse retVal = ((TeaRoom.OperatServices.OperatServicesSoap)(this)).EndGetOperatList(result);
            return retVal.Body.GetOperatListResult;
        }
        
        private System.IAsyncResult OnBeginGetOperatList(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginGetOperatList(callback, asyncState);
        }
        
        private object[] OnEndGetOperatList(System.IAsyncResult result) {
            TeaRoom.OperatServices.T_Operat_User[] retVal = this.EndGetOperatList(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetOperatListCompleted(object state) {
            if ((this.GetOperatListCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetOperatListCompleted(this, new GetOperatListCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetOperatListAsync() {
            this.GetOperatListAsync(null);
        }
        
        public void GetOperatListAsync(object userState) {
            if ((this.onBeginGetOperatListDelegate == null)) {
                this.onBeginGetOperatListDelegate = new BeginOperationDelegate(this.OnBeginGetOperatList);
            }
            if ((this.onEndGetOperatListDelegate == null)) {
                this.onEndGetOperatListDelegate = new EndOperationDelegate(this.OnEndGetOperatList);
            }
            if ((this.onGetOperatListCompletedDelegate == null)) {
                this.onGetOperatListCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetOperatListCompleted);
            }
            base.InvokeAsync(this.onBeginGetOperatListDelegate, null, this.onEndGetOperatListDelegate, this.onGetOperatListCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TeaRoom.OperatServices.SaveOrUpdateOperatResponse TeaRoom.OperatServices.OperatServicesSoap.SaveOrUpdateOperat(TeaRoom.OperatServices.SaveOrUpdateOperatRequest request) {
            return base.Channel.SaveOrUpdateOperat(request);
        }
        
        public int SaveOrUpdateOperat(string Password, string UserName, string OperatName, string Tel, string Active, string OperatGroup, string OperatID) {
            TeaRoom.OperatServices.SaveOrUpdateOperatRequest inValue = new TeaRoom.OperatServices.SaveOrUpdateOperatRequest();
            inValue.Body = new TeaRoom.OperatServices.SaveOrUpdateOperatRequestBody();
            inValue.Body.Password = Password;
            inValue.Body.UserName = UserName;
            inValue.Body.OperatName = OperatName;
            inValue.Body.Tel = Tel;
            inValue.Body.Active = Active;
            inValue.Body.OperatGroup = OperatGroup;
            inValue.Body.OperatID = OperatID;
            TeaRoom.OperatServices.SaveOrUpdateOperatResponse retVal = ((TeaRoom.OperatServices.OperatServicesSoap)(this)).SaveOrUpdateOperat(inValue);
            return retVal.Body.SaveOrUpdateOperatResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult TeaRoom.OperatServices.OperatServicesSoap.BeginSaveOrUpdateOperat(TeaRoom.OperatServices.SaveOrUpdateOperatRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSaveOrUpdateOperat(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginSaveOrUpdateOperat(string Password, string UserName, string OperatName, string Tel, string Active, string OperatGroup, string OperatID, System.AsyncCallback callback, object asyncState) {
            TeaRoom.OperatServices.SaveOrUpdateOperatRequest inValue = new TeaRoom.OperatServices.SaveOrUpdateOperatRequest();
            inValue.Body = new TeaRoom.OperatServices.SaveOrUpdateOperatRequestBody();
            inValue.Body.Password = Password;
            inValue.Body.UserName = UserName;
            inValue.Body.OperatName = OperatName;
            inValue.Body.Tel = Tel;
            inValue.Body.Active = Active;
            inValue.Body.OperatGroup = OperatGroup;
            inValue.Body.OperatID = OperatID;
            return ((TeaRoom.OperatServices.OperatServicesSoap)(this)).BeginSaveOrUpdateOperat(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TeaRoom.OperatServices.SaveOrUpdateOperatResponse TeaRoom.OperatServices.OperatServicesSoap.EndSaveOrUpdateOperat(System.IAsyncResult result) {
            return base.Channel.EndSaveOrUpdateOperat(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public int EndSaveOrUpdateOperat(System.IAsyncResult result) {
            TeaRoom.OperatServices.SaveOrUpdateOperatResponse retVal = ((TeaRoom.OperatServices.OperatServicesSoap)(this)).EndSaveOrUpdateOperat(result);
            return retVal.Body.SaveOrUpdateOperatResult;
        }
        
        private System.IAsyncResult OnBeginSaveOrUpdateOperat(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string Password = ((string)(inValues[0]));
            string UserName = ((string)(inValues[1]));
            string OperatName = ((string)(inValues[2]));
            string Tel = ((string)(inValues[3]));
            string Active = ((string)(inValues[4]));
            string OperatGroup = ((string)(inValues[5]));
            string OperatID = ((string)(inValues[6]));
            return this.BeginSaveOrUpdateOperat(Password, UserName, OperatName, Tel, Active, OperatGroup, OperatID, callback, asyncState);
        }
        
        private object[] OnEndSaveOrUpdateOperat(System.IAsyncResult result) {
            int retVal = this.EndSaveOrUpdateOperat(result);
            return new object[] {
                    retVal};
        }
        
        private void OnSaveOrUpdateOperatCompleted(object state) {
            if ((this.SaveOrUpdateOperatCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SaveOrUpdateOperatCompleted(this, new SaveOrUpdateOperatCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SaveOrUpdateOperatAsync(string Password, string UserName, string OperatName, string Tel, string Active, string OperatGroup, string OperatID) {
            this.SaveOrUpdateOperatAsync(Password, UserName, OperatName, Tel, Active, OperatGroup, OperatID, null);
        }
        
        public void SaveOrUpdateOperatAsync(string Password, string UserName, string OperatName, string Tel, string Active, string OperatGroup, string OperatID, object userState) {
            if ((this.onBeginSaveOrUpdateOperatDelegate == null)) {
                this.onBeginSaveOrUpdateOperatDelegate = new BeginOperationDelegate(this.OnBeginSaveOrUpdateOperat);
            }
            if ((this.onEndSaveOrUpdateOperatDelegate == null)) {
                this.onEndSaveOrUpdateOperatDelegate = new EndOperationDelegate(this.OnEndSaveOrUpdateOperat);
            }
            if ((this.onSaveOrUpdateOperatCompletedDelegate == null)) {
                this.onSaveOrUpdateOperatCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSaveOrUpdateOperatCompleted);
            }
            base.InvokeAsync(this.onBeginSaveOrUpdateOperatDelegate, new object[] {
                        Password,
                        UserName,
                        OperatName,
                        Tel,
                        Active,
                        OperatGroup,
                        OperatID}, this.onEndSaveOrUpdateOperatDelegate, this.onSaveOrUpdateOperatCompletedDelegate, userState);
        }
    }
}
