//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34209
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeaRoom.MemberServices {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Message", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Message : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageStringField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string MessageString {
            get {
                return this.MessageStringField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageStringField, value) != true)) {
                    this.MessageStringField = value;
                    this.RaisePropertyChanged("MessageString");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="T_Members", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class T_Members : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int MemberIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CardNoField;
        
        private System.Nullable<System.DateTime> BirthdayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OpenIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelField;
        
        private System.Nullable<decimal> AmountField;
        
        private System.Nullable<System.DateTime> CreateDateField;
        
        private System.Nullable<int> OperatIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int MemberID {
            get {
                return this.MemberIDField;
            }
            set {
                if ((this.MemberIDField.Equals(value) != true)) {
                    this.MemberIDField = value;
                    this.RaisePropertyChanged("MemberID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Sex {
            get {
                return this.SexField;
            }
            set {
                if ((object.ReferenceEquals(this.SexField, value) != true)) {
                    this.SexField = value;
                    this.RaisePropertyChanged("Sex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string CardNo {
            get {
                return this.CardNoField;
            }
            set {
                if ((object.ReferenceEquals(this.CardNoField, value) != true)) {
                    this.CardNoField = value;
                    this.RaisePropertyChanged("CardNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.Nullable<System.DateTime> Birthday {
            get {
                return this.BirthdayField;
            }
            set {
                if ((this.BirthdayField.Equals(value) != true)) {
                    this.BirthdayField = value;
                    this.RaisePropertyChanged("Birthday");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string OpenID {
            get {
                return this.OpenIDField;
            }
            set {
                if ((object.ReferenceEquals(this.OpenIDField, value) != true)) {
                    this.OpenIDField = value;
                    this.RaisePropertyChanged("OpenID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Tel {
            get {
                return this.TelField;
            }
            set {
                if ((object.ReferenceEquals(this.TelField, value) != true)) {
                    this.TelField = value;
                    this.RaisePropertyChanged("Tel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.Nullable<decimal> Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public System.Nullable<System.DateTime> CreateDate {
            get {
                return this.CreateDateField;
            }
            set {
                if ((this.CreateDateField.Equals(value) != true)) {
                    this.CreateDateField = value;
                    this.RaisePropertyChanged("CreateDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public System.Nullable<int> OperatID {
            get {
                return this.OperatIDField;
            }
            set {
                if ((this.OperatIDField.Equals(value) != true)) {
                    this.OperatIDField = value;
                    this.RaisePropertyChanged("OperatID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MemberServices.MemberServicesSoap")]
    public interface MemberServicesSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 Name 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddMembers", ReplyAction="*")]
        TeaRoom.MemberServices.AddMembersResponse AddMembers(TeaRoom.MemberServices.AddMembersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/AddMembers", ReplyAction="*")]
        System.IAsyncResult BeginAddMembers(TeaRoom.MemberServices.AddMembersRequest request, System.AsyncCallback callback, object asyncState);
        
        TeaRoom.MemberServices.AddMembersResponse EndAddMembers(System.IAsyncResult result);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 strWhere 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMemberList", ReplyAction="*")]
        TeaRoom.MemberServices.GetMemberListResponse GetMemberList(TeaRoom.MemberServices.GetMemberListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/GetMemberList", ReplyAction="*")]
        System.IAsyncResult BeginGetMemberList(TeaRoom.MemberServices.GetMemberListRequest request, System.AsyncCallback callback, object asyncState);
        
        TeaRoom.MemberServices.GetMemberListResponse EndGetMemberList(System.IAsyncResult result);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 Amount 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MemberRecharge", ReplyAction="*")]
        TeaRoom.MemberServices.MemberRechargeResponse MemberRecharge(TeaRoom.MemberServices.MemberRechargeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/MemberRecharge", ReplyAction="*")]
        System.IAsyncResult BeginMemberRecharge(TeaRoom.MemberServices.MemberRechargeRequest request, System.AsyncCallback callback, object asyncState);
        
        TeaRoom.MemberServices.MemberRechargeResponse EndMemberRecharge(System.IAsyncResult result);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 Name 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MemberUpdate", ReplyAction="*")]
        TeaRoom.MemberServices.MemberUpdateResponse MemberUpdate(TeaRoom.MemberServices.MemberUpdateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/MemberUpdate", ReplyAction="*")]
        System.IAsyncResult BeginMemberUpdate(TeaRoom.MemberServices.MemberUpdateRequest request, System.AsyncCallback callback, object asyncState);
        
        TeaRoom.MemberServices.MemberUpdateResponse EndMemberUpdate(System.IAsyncResult result);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 CardNo 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMemberByCardNo", ReplyAction="*")]
        TeaRoom.MemberServices.GetMemberByCardNoResponse GetMemberByCardNo(TeaRoom.MemberServices.GetMemberByCardNoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/GetMemberByCardNo", ReplyAction="*")]
        System.IAsyncResult BeginGetMemberByCardNo(TeaRoom.MemberServices.GetMemberByCardNoRequest request, System.AsyncCallback callback, object asyncState);
        
        TeaRoom.MemberServices.GetMemberByCardNoResponse EndGetMemberByCardNo(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddMembersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddMembers", Namespace="http://tempuri.org/", Order=0)]
        public TeaRoom.MemberServices.AddMembersRequestBody Body;
        
        public AddMembersRequest() {
        }
        
        public AddMembersRequest(TeaRoom.MemberServices.AddMembersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddMembersRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Sex;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string CardNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Birthday;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Tel;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public decimal Amount;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string OperatID;
        
        public AddMembersRequestBody() {
        }
        
        public AddMembersRequestBody(string Name, string Sex, string CardNo, string Birthday, string Tel, decimal Amount, string OperatID) {
            this.Name = Name;
            this.Sex = Sex;
            this.CardNo = CardNo;
            this.Birthday = Birthday;
            this.Tel = Tel;
            this.Amount = Amount;
            this.OperatID = OperatID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddMembersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddMembersResponse", Namespace="http://tempuri.org/", Order=0)]
        public TeaRoom.MemberServices.AddMembersResponseBody Body;
        
        public AddMembersResponse() {
        }
        
        public AddMembersResponse(TeaRoom.MemberServices.AddMembersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddMembersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TeaRoom.MemberServices.Message AddMembersResult;
        
        public AddMembersResponseBody() {
        }
        
        public AddMembersResponseBody(TeaRoom.MemberServices.Message AddMembersResult) {
            this.AddMembersResult = AddMembersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMemberListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMemberList", Namespace="http://tempuri.org/", Order=0)]
        public TeaRoom.MemberServices.GetMemberListRequestBody Body;
        
        public GetMemberListRequest() {
        }
        
        public GetMemberListRequest(TeaRoom.MemberServices.GetMemberListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMemberListRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int Page;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int PageSize;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string strWhere;
        
        public GetMemberListRequestBody() {
        }
        
        public GetMemberListRequestBody(int Page, int PageSize, string strWhere) {
            this.Page = Page;
            this.PageSize = PageSize;
            this.strWhere = strWhere;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMemberListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMemberListResponse", Namespace="http://tempuri.org/", Order=0)]
        public TeaRoom.MemberServices.GetMemberListResponseBody Body;
        
        public GetMemberListResponse() {
        }
        
        public GetMemberListResponse(TeaRoom.MemberServices.GetMemberListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMemberListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TeaRoom.MemberServices.T_Members[] GetMemberListResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int TotalCount;
        
        public GetMemberListResponseBody() {
        }
        
        public GetMemberListResponseBody(TeaRoom.MemberServices.T_Members[] GetMemberListResult, int TotalCount) {
            this.GetMemberListResult = GetMemberListResult;
            this.TotalCount = TotalCount;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MemberRechargeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MemberRecharge", Namespace="http://tempuri.org/", Order=0)]
        public TeaRoom.MemberServices.MemberRechargeRequestBody Body;
        
        public MemberRechargeRequest() {
        }
        
        public MemberRechargeRequest(TeaRoom.MemberServices.MemberRechargeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MemberRechargeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int MemberID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Amount;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string OperatID;
        
        public MemberRechargeRequestBody() {
        }
        
        public MemberRechargeRequestBody(int MemberID, string Amount, string OperatID) {
            this.MemberID = MemberID;
            this.Amount = Amount;
            this.OperatID = OperatID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MemberRechargeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MemberRechargeResponse", Namespace="http://tempuri.org/", Order=0)]
        public TeaRoom.MemberServices.MemberRechargeResponseBody Body;
        
        public MemberRechargeResponse() {
        }
        
        public MemberRechargeResponse(TeaRoom.MemberServices.MemberRechargeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MemberRechargeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TeaRoom.MemberServices.Message MemberRechargeResult;
        
        public MemberRechargeResponseBody() {
        }
        
        public MemberRechargeResponseBody(TeaRoom.MemberServices.Message MemberRechargeResult) {
            this.MemberRechargeResult = MemberRechargeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MemberUpdateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MemberUpdate", Namespace="http://tempuri.org/", Order=0)]
        public TeaRoom.MemberServices.MemberUpdateRequestBody Body;
        
        public MemberUpdateRequest() {
        }
        
        public MemberUpdateRequest(TeaRoom.MemberServices.MemberUpdateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MemberUpdateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int MemberID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Sex;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Birthday;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Tel;
        
        public MemberUpdateRequestBody() {
        }
        
        public MemberUpdateRequestBody(int MemberID, string Name, string Sex, string Birthday, string Tel) {
            this.MemberID = MemberID;
            this.Name = Name;
            this.Sex = Sex;
            this.Birthday = Birthday;
            this.Tel = Tel;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MemberUpdateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MemberUpdateResponse", Namespace="http://tempuri.org/", Order=0)]
        public TeaRoom.MemberServices.MemberUpdateResponseBody Body;
        
        public MemberUpdateResponse() {
        }
        
        public MemberUpdateResponse(TeaRoom.MemberServices.MemberUpdateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MemberUpdateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TeaRoom.MemberServices.Message MemberUpdateResult;
        
        public MemberUpdateResponseBody() {
        }
        
        public MemberUpdateResponseBody(TeaRoom.MemberServices.Message MemberUpdateResult) {
            this.MemberUpdateResult = MemberUpdateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMemberByCardNoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMemberByCardNo", Namespace="http://tempuri.org/", Order=0)]
        public TeaRoom.MemberServices.GetMemberByCardNoRequestBody Body;
        
        public GetMemberByCardNoRequest() {
        }
        
        public GetMemberByCardNoRequest(TeaRoom.MemberServices.GetMemberByCardNoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMemberByCardNoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CardNo;
        
        public GetMemberByCardNoRequestBody() {
        }
        
        public GetMemberByCardNoRequestBody(string CardNo) {
            this.CardNo = CardNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMemberByCardNoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMemberByCardNoResponse", Namespace="http://tempuri.org/", Order=0)]
        public TeaRoom.MemberServices.GetMemberByCardNoResponseBody Body;
        
        public GetMemberByCardNoResponse() {
        }
        
        public GetMemberByCardNoResponse(TeaRoom.MemberServices.GetMemberByCardNoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMemberByCardNoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TeaRoom.MemberServices.T_Members GetMemberByCardNoResult;
        
        public GetMemberByCardNoResponseBody() {
        }
        
        public GetMemberByCardNoResponseBody(TeaRoom.MemberServices.T_Members GetMemberByCardNoResult) {
            this.GetMemberByCardNoResult = GetMemberByCardNoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MemberServicesSoapChannel : TeaRoom.MemberServices.MemberServicesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AddMembersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public AddMembersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public TeaRoom.MemberServices.Message Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((TeaRoom.MemberServices.Message)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetMemberListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetMemberListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int TotalCount {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
        
        public TeaRoom.MemberServices.T_Members[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((TeaRoom.MemberServices.T_Members[])(this.results[1]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MemberRechargeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public MemberRechargeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public TeaRoom.MemberServices.Message Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((TeaRoom.MemberServices.Message)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MemberUpdateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public MemberUpdateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public TeaRoom.MemberServices.Message Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((TeaRoom.MemberServices.Message)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetMemberByCardNoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetMemberByCardNoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public TeaRoom.MemberServices.T_Members Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((TeaRoom.MemberServices.T_Members)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MemberServicesSoapClient : System.ServiceModel.ClientBase<TeaRoom.MemberServices.MemberServicesSoap>, TeaRoom.MemberServices.MemberServicesSoap {
        
        private BeginOperationDelegate onBeginAddMembersDelegate;
        
        private EndOperationDelegate onEndAddMembersDelegate;
        
        private System.Threading.SendOrPostCallback onAddMembersCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetMemberListDelegate;
        
        private EndOperationDelegate onEndGetMemberListDelegate;
        
        private System.Threading.SendOrPostCallback onGetMemberListCompletedDelegate;
        
        private BeginOperationDelegate onBeginMemberRechargeDelegate;
        
        private EndOperationDelegate onEndMemberRechargeDelegate;
        
        private System.Threading.SendOrPostCallback onMemberRechargeCompletedDelegate;
        
        private BeginOperationDelegate onBeginMemberUpdateDelegate;
        
        private EndOperationDelegate onEndMemberUpdateDelegate;
        
        private System.Threading.SendOrPostCallback onMemberUpdateCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetMemberByCardNoDelegate;
        
        private EndOperationDelegate onEndGetMemberByCardNoDelegate;
        
        private System.Threading.SendOrPostCallback onGetMemberByCardNoCompletedDelegate;
        
        public MemberServicesSoapClient() {
        }
        
        public MemberServicesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MemberServicesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MemberServicesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MemberServicesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<AddMembersCompletedEventArgs> AddMembersCompleted;
        
        public event System.EventHandler<GetMemberListCompletedEventArgs> GetMemberListCompleted;
        
        public event System.EventHandler<MemberRechargeCompletedEventArgs> MemberRechargeCompleted;
        
        public event System.EventHandler<MemberUpdateCompletedEventArgs> MemberUpdateCompleted;
        
        public event System.EventHandler<GetMemberByCardNoCompletedEventArgs> GetMemberByCardNoCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TeaRoom.MemberServices.AddMembersResponse TeaRoom.MemberServices.MemberServicesSoap.AddMembers(TeaRoom.MemberServices.AddMembersRequest request) {
            return base.Channel.AddMembers(request);
        }
        
        public TeaRoom.MemberServices.Message AddMembers(string Name, string Sex, string CardNo, string Birthday, string Tel, decimal Amount, string OperatID) {
            TeaRoom.MemberServices.AddMembersRequest inValue = new TeaRoom.MemberServices.AddMembersRequest();
            inValue.Body = new TeaRoom.MemberServices.AddMembersRequestBody();
            inValue.Body.Name = Name;
            inValue.Body.Sex = Sex;
            inValue.Body.CardNo = CardNo;
            inValue.Body.Birthday = Birthday;
            inValue.Body.Tel = Tel;
            inValue.Body.Amount = Amount;
            inValue.Body.OperatID = OperatID;
            TeaRoom.MemberServices.AddMembersResponse retVal = ((TeaRoom.MemberServices.MemberServicesSoap)(this)).AddMembers(inValue);
            return retVal.Body.AddMembersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult TeaRoom.MemberServices.MemberServicesSoap.BeginAddMembers(TeaRoom.MemberServices.AddMembersRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginAddMembers(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginAddMembers(string Name, string Sex, string CardNo, string Birthday, string Tel, decimal Amount, string OperatID, System.AsyncCallback callback, object asyncState) {
            TeaRoom.MemberServices.AddMembersRequest inValue = new TeaRoom.MemberServices.AddMembersRequest();
            inValue.Body = new TeaRoom.MemberServices.AddMembersRequestBody();
            inValue.Body.Name = Name;
            inValue.Body.Sex = Sex;
            inValue.Body.CardNo = CardNo;
            inValue.Body.Birthday = Birthday;
            inValue.Body.Tel = Tel;
            inValue.Body.Amount = Amount;
            inValue.Body.OperatID = OperatID;
            return ((TeaRoom.MemberServices.MemberServicesSoap)(this)).BeginAddMembers(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TeaRoom.MemberServices.AddMembersResponse TeaRoom.MemberServices.MemberServicesSoap.EndAddMembers(System.IAsyncResult result) {
            return base.Channel.EndAddMembers(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public TeaRoom.MemberServices.Message EndAddMembers(System.IAsyncResult result) {
            TeaRoom.MemberServices.AddMembersResponse retVal = ((TeaRoom.MemberServices.MemberServicesSoap)(this)).EndAddMembers(result);
            return retVal.Body.AddMembersResult;
        }
        
        private System.IAsyncResult OnBeginAddMembers(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string Name = ((string)(inValues[0]));
            string Sex = ((string)(inValues[1]));
            string CardNo = ((string)(inValues[2]));
            string Birthday = ((string)(inValues[3]));
            string Tel = ((string)(inValues[4]));
            decimal Amount = ((decimal)(inValues[5]));
            string OperatID = ((string)(inValues[6]));
            return this.BeginAddMembers(Name, Sex, CardNo, Birthday, Tel, Amount, OperatID, callback, asyncState);
        }
        
        private object[] OnEndAddMembers(System.IAsyncResult result) {
            TeaRoom.MemberServices.Message retVal = this.EndAddMembers(result);
            return new object[] {
                    retVal};
        }
        
        private void OnAddMembersCompleted(object state) {
            if ((this.AddMembersCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.AddMembersCompleted(this, new AddMembersCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void AddMembersAsync(string Name, string Sex, string CardNo, string Birthday, string Tel, decimal Amount, string OperatID) {
            this.AddMembersAsync(Name, Sex, CardNo, Birthday, Tel, Amount, OperatID, null);
        }
        
        public void AddMembersAsync(string Name, string Sex, string CardNo, string Birthday, string Tel, decimal Amount, string OperatID, object userState) {
            if ((this.onBeginAddMembersDelegate == null)) {
                this.onBeginAddMembersDelegate = new BeginOperationDelegate(this.OnBeginAddMembers);
            }
            if ((this.onEndAddMembersDelegate == null)) {
                this.onEndAddMembersDelegate = new EndOperationDelegate(this.OnEndAddMembers);
            }
            if ((this.onAddMembersCompletedDelegate == null)) {
                this.onAddMembersCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnAddMembersCompleted);
            }
            base.InvokeAsync(this.onBeginAddMembersDelegate, new object[] {
                        Name,
                        Sex,
                        CardNo,
                        Birthday,
                        Tel,
                        Amount,
                        OperatID}, this.onEndAddMembersDelegate, this.onAddMembersCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TeaRoom.MemberServices.GetMemberListResponse TeaRoom.MemberServices.MemberServicesSoap.GetMemberList(TeaRoom.MemberServices.GetMemberListRequest request) {
            return base.Channel.GetMemberList(request);
        }
        
        public TeaRoom.MemberServices.T_Members[] GetMemberList(int Page, int PageSize, string strWhere, out int TotalCount) {
            TeaRoom.MemberServices.GetMemberListRequest inValue = new TeaRoom.MemberServices.GetMemberListRequest();
            inValue.Body = new TeaRoom.MemberServices.GetMemberListRequestBody();
            inValue.Body.Page = Page;
            inValue.Body.PageSize = PageSize;
            inValue.Body.strWhere = strWhere;
            TeaRoom.MemberServices.GetMemberListResponse retVal = ((TeaRoom.MemberServices.MemberServicesSoap)(this)).GetMemberList(inValue);
            TotalCount = retVal.Body.TotalCount;
            return retVal.Body.GetMemberListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult TeaRoom.MemberServices.MemberServicesSoap.BeginGetMemberList(TeaRoom.MemberServices.GetMemberListRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetMemberList(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetMemberList(int Page, int PageSize, string strWhere, System.AsyncCallback callback, object asyncState) {
            TeaRoom.MemberServices.GetMemberListRequest inValue = new TeaRoom.MemberServices.GetMemberListRequest();
            inValue.Body = new TeaRoom.MemberServices.GetMemberListRequestBody();
            inValue.Body.Page = Page;
            inValue.Body.PageSize = PageSize;
            inValue.Body.strWhere = strWhere;
            return ((TeaRoom.MemberServices.MemberServicesSoap)(this)).BeginGetMemberList(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TeaRoom.MemberServices.GetMemberListResponse TeaRoom.MemberServices.MemberServicesSoap.EndGetMemberList(System.IAsyncResult result) {
            return base.Channel.EndGetMemberList(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public TeaRoom.MemberServices.T_Members[] EndGetMemberList(System.IAsyncResult result, out int TotalCount) {
            TeaRoom.MemberServices.GetMemberListResponse retVal = ((TeaRoom.MemberServices.MemberServicesSoap)(this)).EndGetMemberList(result);
            TotalCount = retVal.Body.TotalCount;
            return retVal.Body.GetMemberListResult;
        }
        
        private System.IAsyncResult OnBeginGetMemberList(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int Page = ((int)(inValues[0]));
            int PageSize = ((int)(inValues[1]));
            string strWhere = ((string)(inValues[2]));
            return this.BeginGetMemberList(Page, PageSize, strWhere, callback, asyncState);
        }
        
        private object[] OnEndGetMemberList(System.IAsyncResult result) {
            int TotalCount = this.GetDefaultValueForInitialization<int>();
            TeaRoom.MemberServices.T_Members[] retVal = this.EndGetMemberList(result, out TotalCount);
            return new object[] {
                    TotalCount,
                    retVal};
        }
        
        private void OnGetMemberListCompleted(object state) {
            if ((this.GetMemberListCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetMemberListCompleted(this, new GetMemberListCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetMemberListAsync(int Page, int PageSize, string strWhere) {
            this.GetMemberListAsync(Page, PageSize, strWhere, null);
        }
        
        public void GetMemberListAsync(int Page, int PageSize, string strWhere, object userState) {
            if ((this.onBeginGetMemberListDelegate == null)) {
                this.onBeginGetMemberListDelegate = new BeginOperationDelegate(this.OnBeginGetMemberList);
            }
            if ((this.onEndGetMemberListDelegate == null)) {
                this.onEndGetMemberListDelegate = new EndOperationDelegate(this.OnEndGetMemberList);
            }
            if ((this.onGetMemberListCompletedDelegate == null)) {
                this.onGetMemberListCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetMemberListCompleted);
            }
            base.InvokeAsync(this.onBeginGetMemberListDelegate, new object[] {
                        Page,
                        PageSize,
                        strWhere}, this.onEndGetMemberListDelegate, this.onGetMemberListCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TeaRoom.MemberServices.MemberRechargeResponse TeaRoom.MemberServices.MemberServicesSoap.MemberRecharge(TeaRoom.MemberServices.MemberRechargeRequest request) {
            return base.Channel.MemberRecharge(request);
        }
        
        public TeaRoom.MemberServices.Message MemberRecharge(int MemberID, string Amount, string OperatID) {
            TeaRoom.MemberServices.MemberRechargeRequest inValue = new TeaRoom.MemberServices.MemberRechargeRequest();
            inValue.Body = new TeaRoom.MemberServices.MemberRechargeRequestBody();
            inValue.Body.MemberID = MemberID;
            inValue.Body.Amount = Amount;
            inValue.Body.OperatID = OperatID;
            TeaRoom.MemberServices.MemberRechargeResponse retVal = ((TeaRoom.MemberServices.MemberServicesSoap)(this)).MemberRecharge(inValue);
            return retVal.Body.MemberRechargeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult TeaRoom.MemberServices.MemberServicesSoap.BeginMemberRecharge(TeaRoom.MemberServices.MemberRechargeRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginMemberRecharge(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginMemberRecharge(int MemberID, string Amount, string OperatID, System.AsyncCallback callback, object asyncState) {
            TeaRoom.MemberServices.MemberRechargeRequest inValue = new TeaRoom.MemberServices.MemberRechargeRequest();
            inValue.Body = new TeaRoom.MemberServices.MemberRechargeRequestBody();
            inValue.Body.MemberID = MemberID;
            inValue.Body.Amount = Amount;
            inValue.Body.OperatID = OperatID;
            return ((TeaRoom.MemberServices.MemberServicesSoap)(this)).BeginMemberRecharge(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TeaRoom.MemberServices.MemberRechargeResponse TeaRoom.MemberServices.MemberServicesSoap.EndMemberRecharge(System.IAsyncResult result) {
            return base.Channel.EndMemberRecharge(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public TeaRoom.MemberServices.Message EndMemberRecharge(System.IAsyncResult result) {
            TeaRoom.MemberServices.MemberRechargeResponse retVal = ((TeaRoom.MemberServices.MemberServicesSoap)(this)).EndMemberRecharge(result);
            return retVal.Body.MemberRechargeResult;
        }
        
        private System.IAsyncResult OnBeginMemberRecharge(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int MemberID = ((int)(inValues[0]));
            string Amount = ((string)(inValues[1]));
            string OperatID = ((string)(inValues[2]));
            return this.BeginMemberRecharge(MemberID, Amount, OperatID, callback, asyncState);
        }
        
        private object[] OnEndMemberRecharge(System.IAsyncResult result) {
            TeaRoom.MemberServices.Message retVal = this.EndMemberRecharge(result);
            return new object[] {
                    retVal};
        }
        
        private void OnMemberRechargeCompleted(object state) {
            if ((this.MemberRechargeCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.MemberRechargeCompleted(this, new MemberRechargeCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void MemberRechargeAsync(int MemberID, string Amount, string OperatID) {
            this.MemberRechargeAsync(MemberID, Amount, OperatID, null);
        }
        
        public void MemberRechargeAsync(int MemberID, string Amount, string OperatID, object userState) {
            if ((this.onBeginMemberRechargeDelegate == null)) {
                this.onBeginMemberRechargeDelegate = new BeginOperationDelegate(this.OnBeginMemberRecharge);
            }
            if ((this.onEndMemberRechargeDelegate == null)) {
                this.onEndMemberRechargeDelegate = new EndOperationDelegate(this.OnEndMemberRecharge);
            }
            if ((this.onMemberRechargeCompletedDelegate == null)) {
                this.onMemberRechargeCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnMemberRechargeCompleted);
            }
            base.InvokeAsync(this.onBeginMemberRechargeDelegate, new object[] {
                        MemberID,
                        Amount,
                        OperatID}, this.onEndMemberRechargeDelegate, this.onMemberRechargeCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TeaRoom.MemberServices.MemberUpdateResponse TeaRoom.MemberServices.MemberServicesSoap.MemberUpdate(TeaRoom.MemberServices.MemberUpdateRequest request) {
            return base.Channel.MemberUpdate(request);
        }
        
        public TeaRoom.MemberServices.Message MemberUpdate(int MemberID, string Name, string Sex, string Birthday, string Tel) {
            TeaRoom.MemberServices.MemberUpdateRequest inValue = new TeaRoom.MemberServices.MemberUpdateRequest();
            inValue.Body = new TeaRoom.MemberServices.MemberUpdateRequestBody();
            inValue.Body.MemberID = MemberID;
            inValue.Body.Name = Name;
            inValue.Body.Sex = Sex;
            inValue.Body.Birthday = Birthday;
            inValue.Body.Tel = Tel;
            TeaRoom.MemberServices.MemberUpdateResponse retVal = ((TeaRoom.MemberServices.MemberServicesSoap)(this)).MemberUpdate(inValue);
            return retVal.Body.MemberUpdateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult TeaRoom.MemberServices.MemberServicesSoap.BeginMemberUpdate(TeaRoom.MemberServices.MemberUpdateRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginMemberUpdate(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginMemberUpdate(int MemberID, string Name, string Sex, string Birthday, string Tel, System.AsyncCallback callback, object asyncState) {
            TeaRoom.MemberServices.MemberUpdateRequest inValue = new TeaRoom.MemberServices.MemberUpdateRequest();
            inValue.Body = new TeaRoom.MemberServices.MemberUpdateRequestBody();
            inValue.Body.MemberID = MemberID;
            inValue.Body.Name = Name;
            inValue.Body.Sex = Sex;
            inValue.Body.Birthday = Birthday;
            inValue.Body.Tel = Tel;
            return ((TeaRoom.MemberServices.MemberServicesSoap)(this)).BeginMemberUpdate(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TeaRoom.MemberServices.MemberUpdateResponse TeaRoom.MemberServices.MemberServicesSoap.EndMemberUpdate(System.IAsyncResult result) {
            return base.Channel.EndMemberUpdate(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public TeaRoom.MemberServices.Message EndMemberUpdate(System.IAsyncResult result) {
            TeaRoom.MemberServices.MemberUpdateResponse retVal = ((TeaRoom.MemberServices.MemberServicesSoap)(this)).EndMemberUpdate(result);
            return retVal.Body.MemberUpdateResult;
        }
        
        private System.IAsyncResult OnBeginMemberUpdate(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int MemberID = ((int)(inValues[0]));
            string Name = ((string)(inValues[1]));
            string Sex = ((string)(inValues[2]));
            string Birthday = ((string)(inValues[3]));
            string Tel = ((string)(inValues[4]));
            return this.BeginMemberUpdate(MemberID, Name, Sex, Birthday, Tel, callback, asyncState);
        }
        
        private object[] OnEndMemberUpdate(System.IAsyncResult result) {
            TeaRoom.MemberServices.Message retVal = this.EndMemberUpdate(result);
            return new object[] {
                    retVal};
        }
        
        private void OnMemberUpdateCompleted(object state) {
            if ((this.MemberUpdateCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.MemberUpdateCompleted(this, new MemberUpdateCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void MemberUpdateAsync(int MemberID, string Name, string Sex, string Birthday, string Tel) {
            this.MemberUpdateAsync(MemberID, Name, Sex, Birthday, Tel, null);
        }
        
        public void MemberUpdateAsync(int MemberID, string Name, string Sex, string Birthday, string Tel, object userState) {
            if ((this.onBeginMemberUpdateDelegate == null)) {
                this.onBeginMemberUpdateDelegate = new BeginOperationDelegate(this.OnBeginMemberUpdate);
            }
            if ((this.onEndMemberUpdateDelegate == null)) {
                this.onEndMemberUpdateDelegate = new EndOperationDelegate(this.OnEndMemberUpdate);
            }
            if ((this.onMemberUpdateCompletedDelegate == null)) {
                this.onMemberUpdateCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnMemberUpdateCompleted);
            }
            base.InvokeAsync(this.onBeginMemberUpdateDelegate, new object[] {
                        MemberID,
                        Name,
                        Sex,
                        Birthday,
                        Tel}, this.onEndMemberUpdateDelegate, this.onMemberUpdateCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TeaRoom.MemberServices.GetMemberByCardNoResponse TeaRoom.MemberServices.MemberServicesSoap.GetMemberByCardNo(TeaRoom.MemberServices.GetMemberByCardNoRequest request) {
            return base.Channel.GetMemberByCardNo(request);
        }
        
        public TeaRoom.MemberServices.T_Members GetMemberByCardNo(string CardNo) {
            TeaRoom.MemberServices.GetMemberByCardNoRequest inValue = new TeaRoom.MemberServices.GetMemberByCardNoRequest();
            inValue.Body = new TeaRoom.MemberServices.GetMemberByCardNoRequestBody();
            inValue.Body.CardNo = CardNo;
            TeaRoom.MemberServices.GetMemberByCardNoResponse retVal = ((TeaRoom.MemberServices.MemberServicesSoap)(this)).GetMemberByCardNo(inValue);
            return retVal.Body.GetMemberByCardNoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult TeaRoom.MemberServices.MemberServicesSoap.BeginGetMemberByCardNo(TeaRoom.MemberServices.GetMemberByCardNoRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetMemberByCardNo(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetMemberByCardNo(string CardNo, System.AsyncCallback callback, object asyncState) {
            TeaRoom.MemberServices.GetMemberByCardNoRequest inValue = new TeaRoom.MemberServices.GetMemberByCardNoRequest();
            inValue.Body = new TeaRoom.MemberServices.GetMemberByCardNoRequestBody();
            inValue.Body.CardNo = CardNo;
            return ((TeaRoom.MemberServices.MemberServicesSoap)(this)).BeginGetMemberByCardNo(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TeaRoom.MemberServices.GetMemberByCardNoResponse TeaRoom.MemberServices.MemberServicesSoap.EndGetMemberByCardNo(System.IAsyncResult result) {
            return base.Channel.EndGetMemberByCardNo(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public TeaRoom.MemberServices.T_Members EndGetMemberByCardNo(System.IAsyncResult result) {
            TeaRoom.MemberServices.GetMemberByCardNoResponse retVal = ((TeaRoom.MemberServices.MemberServicesSoap)(this)).EndGetMemberByCardNo(result);
            return retVal.Body.GetMemberByCardNoResult;
        }
        
        private System.IAsyncResult OnBeginGetMemberByCardNo(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string CardNo = ((string)(inValues[0]));
            return this.BeginGetMemberByCardNo(CardNo, callback, asyncState);
        }
        
        private object[] OnEndGetMemberByCardNo(System.IAsyncResult result) {
            TeaRoom.MemberServices.T_Members retVal = this.EndGetMemberByCardNo(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetMemberByCardNoCompleted(object state) {
            if ((this.GetMemberByCardNoCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetMemberByCardNoCompleted(this, new GetMemberByCardNoCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetMemberByCardNoAsync(string CardNo) {
            this.GetMemberByCardNoAsync(CardNo, null);
        }
        
        public void GetMemberByCardNoAsync(string CardNo, object userState) {
            if ((this.onBeginGetMemberByCardNoDelegate == null)) {
                this.onBeginGetMemberByCardNoDelegate = new BeginOperationDelegate(this.OnBeginGetMemberByCardNo);
            }
            if ((this.onEndGetMemberByCardNoDelegate == null)) {
                this.onEndGetMemberByCardNoDelegate = new EndOperationDelegate(this.OnEndGetMemberByCardNo);
            }
            if ((this.onGetMemberByCardNoCompletedDelegate == null)) {
                this.onGetMemberByCardNoCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetMemberByCardNoCompleted);
            }
            base.InvokeAsync(this.onBeginGetMemberByCardNoDelegate, new object[] {
                        CardNo}, this.onEndGetMemberByCardNoDelegate, this.onGetMemberByCardNoCompletedDelegate, userState);
        }
    }
}
